#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\instrument_editor.ui'
#
# Created: Thu Apr 30 08:05:56 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 536)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.default_value_widget = QtWidgets.QWidget(Form)
        self.default_value_widget.setObjectName("default_value_widget")
        self.default_value_widget_2 = QtWidgets.QHBoxLayout(self.default_value_widget)
        self.default_value_widget_2.setContentsMargins(0, 0, 0, 0)
        self.default_value_widget_2.setObjectName("default_value_widget_2")
        self.label = QtWidgets.QLabel(self.default_value_widget)
        self.label.setObjectName("label")
        self.default_value_widget_2.addWidget(self.label)
        self.default_value_edit = QtWidgets.QLineEdit(self.default_value_widget)
        self.default_value_edit.setObjectName("default_value_edit")
        self.default_value_widget_2.addWidget(self.default_value_edit)
        self.default_value_ed_button = QtWidgets.QPushButton(self.default_value_widget)
        self.default_value_ed_button.setObjectName("default_value_ed_button")
        self.default_value_widget_2.addWidget(self.default_value_ed_button)
        self.verticalLayout.addWidget(self.default_value_widget)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_calibration_button = QtWidgets.QPushButton(self.widget_2)
        self.new_calibration_button.setObjectName("new_calibration_button")
        self.horizontalLayout_2.addWidget(self.new_calibration_button)
        spacerItem = QtWidgets.QSpacerItem(502, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.calibration_table = QtWidgets.QTableWidget(self.groupBox)
        self.calibration_table.setObjectName("calibration_table")
        self.calibration_table.setColumnCount(2)
        self.calibration_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.calibration_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibration_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.calibration_table)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.calibration_value_widget = QtWidgets.QWidget(self.groupBox_2)
        self.calibration_value_widget.setObjectName("calibration_value_widget")
        self.calibration_value_widget_2 = QtWidgets.QHBoxLayout(self.calibration_value_widget)
        self.calibration_value_widget_2.setContentsMargins(0, 0, 0, 0)
        self.calibration_value_widget_2.setObjectName("calibration_value_widget_2")
        self.label_2 = QtWidgets.QLabel(self.calibration_value_widget)
        self.label_2.setObjectName("label_2")
        self.calibration_value_widget_2.addWidget(self.label_2)
        self.calibration_value_edit = QtWidgets.QLineEdit(self.calibration_value_widget)
        self.calibration_value_edit.setObjectName("calibration_value_edit")
        self.calibration_value_widget_2.addWidget(self.calibration_value_edit)
        self.calibration_value_ed_button = QtWidgets.QPushButton(self.calibration_value_widget)
        self.calibration_value_ed_button.setObjectName("calibration_value_ed_button")
        self.calibration_value_widget_2.addWidget(self.calibration_value_ed_button)
        self.verticalLayout_3.addWidget(self.calibration_value_widget)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.new_sample = QtWidgets.QPushButton(self.widget_3)
        self.new_sample.setObjectName("new_sample")
        self.horizontalLayout_3.addWidget(self.new_sample)
        self.choose_sample = QtWidgets.QPushButton(self.widget_3)
        self.choose_sample.setObjectName("choose_sample")
        self.horizontalLayout_3.addWidget(self.choose_sample)
        spacerItem1 = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.sample_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.sample_table.setObjectName("sample_table")
        self.sample_table.setColumnCount(0)
        self.sample_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.sample_table)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Paramètres de départ :"))
        self.default_value_ed_button.setText(_translate("Form", "Editer"))
        self.groupBox.setTitle(_translate("Form", "Calibration :"))
        self.new_calibration_button.setText(_translate("Form", "Nouvelle"))
        item = self.calibration_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nom"))
        item = self.calibration_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date"))
        self.groupBox_2.setTitle(_translate("Form", "Détail de la calibration :"))
        self.label_2.setText(_translate("Form", "valeur calibration :"))
        self.calibration_value_ed_button.setText(_translate("Form", "éditer"))
        self.new_sample.setText(_translate("Form", "nouvel échantillon"))
        self.choose_sample.setText(_translate("Form", "choisir échantillon"))

