#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sample_editor.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_box = QtWidgets.QGroupBox(Form)
        self.model_box.setObjectName("model_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.model_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.model_box)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_model_button = QtWidgets.QPushButton(self.widget_2)
        self.add_model_button.setObjectName("add_model_button")
        self.horizontalLayout_2.addWidget(self.add_model_button)
        self.copy_button = QtWidgets.QPushButton(self.widget_2)
        self.copy_button.setObjectName("copy_button")
        self.horizontalLayout_2.addWidget(self.copy_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.model_table = QtWidgets.QTableWidget(self.model_box)
        self.model_table.setObjectName("model_table")
        self.model_table.setColumnCount(4)
        self.model_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.model_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.model_table)
        self.verticalLayout.addWidget(self.model_box)
        self.data_box = QtWidgets.QGroupBox(Form)
        self.data_box.setObjectName("data_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.data_box)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_exp_data_button = QtWidgets.QPushButton(self.widget)
        self.add_exp_data_button.setObjectName("add_exp_data_button")
        self.horizontalLayout.addWidget(self.add_exp_data_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget)
        self.exp_data_table = QtWidgets.QTableWidget(self.data_box)
        self.exp_data_table.setObjectName("exp_data_table")
        self.exp_data_table.setColumnCount(3)
        self.exp_data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.exp_data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.exp_data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.exp_data_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout_2.addWidget(self.exp_data_table)
        self.verticalLayout.addWidget(self.data_box)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Sample editor")
        self.model_box.setTitle("Model: ")
        self.add_model_button.setText("Add")
        self.copy_button.setText("Duplicate")
        item = self.model_table.horizontalHeaderItem(0)
        item.setText("Name")
        item = self.model_table.horizontalHeaderItem(1)
        item.setText("Atmosphere")
        item = self.model_table.horizontalHeaderItem(2)
        item.setText("Substrate")
        item = self.model_table.horizontalHeaderItem(3)
        item.setText("Layers")
        self.data_box.setTitle("Experimental data: ")
        self.add_exp_data_button.setText("Add")
        item = self.exp_data_table.horizontalHeaderItem(0)
        item.setText("Name")
        item = self.exp_data_table.horizontalHeaderItem(1)
        item.setText("Intrument")
        item = self.exp_data_table.horizontalHeaderItem(2)
        item.setText("2 theta scale")

