#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\full_analysis_windows.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(649, 515)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.main_tab = QtGui.QTabWidget(Form)
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.category_combo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_combo.sizePolicy().hasHeightForWidth())
        self.category_combo.setSizePolicy(sizePolicy)
        self.category_combo.setObjectName(_fromUtf8("category_combo"))
        self.horizontalLayout.addWidget(self.category_combo)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.choose_data_combo = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_data_combo.sizePolicy().hasHeightForWidth())
        self.choose_data_combo.setSizePolicy(sizePolicy)
        self.choose_data_combo.setObjectName(_fromUtf8("choose_data_combo"))
        self.horizontalLayout.addWidget(self.choose_data_combo)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.add_result_button = QtGui.QPushButton(self.widget_3)
        self.add_result_button.setObjectName(_fromUtf8("add_result_button"))
        self.horizontalLayout_3.addWidget(self.add_result_button)
        self.clear_button = QtGui.QPushButton(self.widget_3)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.horizontalLayout_3.addWidget(self.clear_button)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.export_widget = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_widget.sizePolicy().hasHeightForWidth())
        self.export_widget.setSizePolicy(sizePolicy)
        self.export_widget.setObjectName(_fromUtf8("export_widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.export_widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.export_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.copy_select_button = QtGui.QPushButton(self.export_widget)
        self.copy_select_button.setObjectName(_fromUtf8("copy_select_button"))
        self.horizontalLayout_2.addWidget(self.copy_select_button)
        self.copy_data_button = QtGui.QPushButton(self.export_widget)
        self.copy_data_button.setObjectName(_fromUtf8("copy_data_button"))
        self.horizontalLayout_2.addWidget(self.copy_data_button)
        self.save_data_button = QtGui.QPushButton(self.export_widget)
        self.save_data_button.setObjectName(_fromUtf8("save_data_button"))
        self.horizontalLayout_2.addWidget(self.save_data_button)
        self.verticalLayout_3.addWidget(self.export_widget)
        self.fom_widget = QtGui.QWidget(self.tab)
        self.fom_widget.setObjectName(_fromUtf8("fom_widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fom_widget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.fom_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fom_selector = QtGui.QComboBox(self.fom_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_selector.sizePolicy().hasHeightForWidth())
        self.fom_selector.setSizePolicy(sizePolicy)
        self.fom_selector.setObjectName(_fromUtf8("fom_selector"))
        self.horizontalLayout_4.addWidget(self.fom_selector)
        self.fom_label = QtGui.QLabel(self.fom_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_label.sizePolicy().hasHeightForWidth())
        self.fom_label.setSizePolicy(sizePolicy)
        self.fom_label.setObjectName(_fromUtf8("fom_label"))
        self.horizontalLayout_4.addWidget(self.fom_label)
        self.fom_line = QtGui.QLineEdit(self.fom_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_line.sizePolicy().hasHeightForWidth())
        self.fom_line.setSizePolicy(sizePolicy)
        self.fom_line.setObjectName(_fromUtf8("fom_line"))
        self.horizontalLayout_4.addWidget(self.fom_line)
        self.verticalLayout_3.addWidget(self.fom_widget)
        self.widget_2 = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.data_layout = QtGui.QVBoxLayout(self.widget_2)
        self.data_layout.setMargin(0)
        self.data_layout.setSpacing(0)
        self.data_layout.setObjectName(_fromUtf8("data_layout"))
        self.data_widget = QtGui.QWidget(self.widget_2)
        self.data_widget.setObjectName(_fromUtf8("data_widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.data_widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.data_layout.addWidget(self.data_widget)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.main_tab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_17.setMargin(0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.widget_13 = QtGui.QWidget(self.tab_2)
        self.widget_13.setObjectName(_fromUtf8("widget_13"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_13)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.widget_14 = QtGui.QWidget(self.groupBox_3)
        self.widget_14.setObjectName(_fromUtf8("widget_14"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_19 = QtGui.QLabel(self.widget_14)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_20.addWidget(self.label_19)
        self.parameter_selector = QtGui.QComboBox(self.widget_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_selector.sizePolicy().hasHeightForWidth())
        self.parameter_selector.setSizePolicy(sizePolicy)
        self.parameter_selector.setObjectName(_fromUtf8("parameter_selector"))
        self.horizontalLayout_20.addWidget(self.parameter_selector)
        self.parameter_option_button = QtGui.QPushButton(self.widget_14)
        self.parameter_option_button.setObjectName(_fromUtf8("parameter_option_button"))
        self.horizontalLayout_20.addWidget(self.parameter_option_button)
        self.verticalLayout_15.addWidget(self.widget_14)
        self.parameter_widget = QtGui.QWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_widget.sizePolicy().hasHeightForWidth())
        self.parameter_widget.setSizePolicy(sizePolicy)
        self.parameter_widget.setObjectName(_fromUtf8("parameter_widget"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.parameter_widget)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_15.addWidget(self.parameter_widget)
        self.horizontalLayout_19.addWidget(self.groupBox_3)
        self.parameter_widget_2 = QtGui.QTableWidget(self.widget_13)
        self.parameter_widget_2.setObjectName(_fromUtf8("parameter_widget_2"))
        self.parameter_widget_2.setColumnCount(5)
        self.parameter_widget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_19.addWidget(self.parameter_widget_2)
        self.verticalLayout_17.addWidget(self.widget_13)
        self.data_history_widget = QtGui.QWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_history_widget.sizePolicy().hasHeightForWidth())
        self.data_history_widget.setSizePolicy(sizePolicy)
        self.data_history_widget.setObjectName(_fromUtf8("data_history_widget"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.data_history_widget)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_17.addWidget(self.data_history_widget)
        self.main_tab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.widget_17 = QtGui.QWidget(self.tab_3)
        self.widget_17.setObjectName(_fromUtf8("widget_17"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widget_17)
        self.horizontalLayout_22.setContentsMargins(0, 3, 3, 3)
        self.horizontalLayout_22.setSpacing(3)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_21 = QtGui.QLabel(self.widget_17)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_22.addWidget(self.label_21)
        self.start_label = QtGui.QLabel(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_label.sizePolicy().hasHeightForWidth())
        self.start_label.setSizePolicy(sizePolicy)
        self.start_label.setText(_fromUtf8(""))
        self.start_label.setObjectName(_fromUtf8("start_label"))
        self.horizontalLayout_22.addWidget(self.start_label)
        self.verticalLayout_18.addWidget(self.widget_17)
        self.widget_16 = QtGui.QWidget(self.tab_3)
        self.widget_16.setObjectName(_fromUtf8("widget_16"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widget_16)
        self.horizontalLayout_21.setMargin(3)
        self.horizontalLayout_21.setSpacing(3)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_20 = QtGui.QLabel(self.widget_16)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_21.addWidget(self.label_20)
        self.end_label = QtGui.QLabel(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_label.sizePolicy().hasHeightForWidth())
        self.end_label.setSizePolicy(sizePolicy)
        self.end_label.setText(_fromUtf8(""))
        self.end_label.setObjectName(_fromUtf8("end_label"))
        self.horizontalLayout_21.addWidget(self.end_label)
        self.verticalLayout_18.addWidget(self.widget_16)
        self.widget_18 = QtGui.QWidget(self.tab_3)
        self.widget_18.setObjectName(_fromUtf8("widget_18"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.widget_18)
        self.horizontalLayout_23.setContentsMargins(0, 3, 3, 3)
        self.horizontalLayout_23.setSpacing(3)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_22 = QtGui.QLabel(self.widget_18)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_23.addWidget(self.label_22)
        self.foms_label = QtGui.QLabel(self.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foms_label.sizePolicy().hasHeightForWidth())
        self.foms_label.setSizePolicy(sizePolicy)
        self.foms_label.setText(_fromUtf8(""))
        self.foms_label.setObjectName(_fromUtf8("foms_label"))
        self.horizontalLayout_23.addWidget(self.foms_label)
        self.verticalLayout_18.addWidget(self.widget_18)
        self.widget_19 = QtGui.QWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setObjectName(_fromUtf8("widget_19"))
        self.verticalLayout_18.addWidget(self.widget_19)
        self.main_tab.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslateUi(Form)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle("Full analysis window")
        self.label_5.setText("Category: ")
        self.label.setText("Data to visualize: ")
        self.label_3.setText("Data overlay")
        self.add_result_button.setText("Result")
        self.clear_button.setText("Clean")
        self.label_2.setText("Export")
        self.copy_select_button.setText("Copy selection")
        self.copy_data_button.setText("Copy")
        self.save_data_button.setText("Save")
        self.label_4.setText("FOM formula: ")
        self.fom_label.setText("FOM: ")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab), "Data analysis")
        self.groupBox_3.setTitle("Parameters history")
        self.label_19.setText("Parameter")
        self.parameter_option_button.setText("Options")
        item = self.parameter_widget_2.horizontalHeaderItem(0)
        item.setText("Parameter")
        item = self.parameter_widget_2.horizontalHeaderItem(1)
        item.setText("Value")
        item = self.parameter_widget_2.horizontalHeaderItem(2)
        item.setText("Lower bound")
        item = self.parameter_widget_2.horizontalHeaderItem(3)
        item.setText("Upper bound")
        item = self.parameter_widget_2.horizontalHeaderItem(4)
        item.setText("Error")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_2), "Parameters and evolution")
        self.label_21.setText("Start")
        self.label_20.setText("End")
        self.label_22.setText("FOM: ")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_3), "General information")

