#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\full_analysis_windows.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(649, 515)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(Form)
        self.main_tab.setObjectName("main_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.category_combo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category_combo.sizePolicy().hasHeightForWidth())
        self.category_combo.setSizePolicy(sizePolicy)
        self.category_combo.setObjectName("category_combo")
        self.horizontalLayout.addWidget(self.category_combo)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.choose_data_combo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_data_combo.sizePolicy().hasHeightForWidth())
        self.choose_data_combo.setSizePolicy(sizePolicy)
        self.choose_data_combo.setObjectName("choose_data_combo")
        self.horizontalLayout.addWidget(self.choose_data_combo)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.add_result_button = QtWidgets.QPushButton(self.widget_3)
        self.add_result_button.setObjectName("add_result_button")
        self.horizontalLayout_3.addWidget(self.add_result_button)
        self.clear_button = QtWidgets.QPushButton(self.widget_3)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_3.addWidget(self.clear_button)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.export_widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_widget.sizePolicy().hasHeightForWidth())
        self.export_widget.setSizePolicy(sizePolicy)
        self.export_widget.setObjectName("export_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.export_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.export_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.copy_select_button = QtWidgets.QPushButton(self.export_widget)
        self.copy_select_button.setObjectName("copy_select_button")
        self.horizontalLayout_2.addWidget(self.copy_select_button)
        self.copy_data_button = QtWidgets.QPushButton(self.export_widget)
        self.copy_data_button.setObjectName("copy_data_button")
        self.horizontalLayout_2.addWidget(self.copy_data_button)
        self.save_data_button = QtWidgets.QPushButton(self.export_widget)
        self.save_data_button.setObjectName("save_data_button")
        self.horizontalLayout_2.addWidget(self.save_data_button)
        self.verticalLayout_3.addWidget(self.export_widget)
        self.fom_widget = QtWidgets.QWidget(self.tab)
        self.fom_widget.setObjectName("fom_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fom_widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fom_selector = QtWidgets.QComboBox(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_selector.sizePolicy().hasHeightForWidth())
        self.fom_selector.setSizePolicy(sizePolicy)
        self.fom_selector.setObjectName("fom_selector")
        self.horizontalLayout_4.addWidget(self.fom_selector)
        self.fom_label = QtWidgets.QLabel(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_label.sizePolicy().hasHeightForWidth())
        self.fom_label.setSizePolicy(sizePolicy)
        self.fom_label.setObjectName("fom_label")
        self.horizontalLayout_4.addWidget(self.fom_label)
        self.fom_line = QtWidgets.QLineEdit(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_line.sizePolicy().hasHeightForWidth())
        self.fom_line.setSizePolicy(sizePolicy)
        self.fom_line.setObjectName("fom_line")
        self.horizontalLayout_4.addWidget(self.fom_line)
        self.verticalLayout_3.addWidget(self.fom_widget)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.data_layout = QtWidgets.QVBoxLayout(self.widget_2)
        self.data_layout.setContentsMargins(0, 0, 0, 0)
        self.data_layout.setSpacing(0)
        self.data_layout.setObjectName("data_layout")
        self.data_widget = QtWidgets.QWidget(self.widget_2)
        self.data_widget.setObjectName("data_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.data_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.data_layout.addWidget(self.data_widget)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.main_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_13 = QtWidgets.QWidget(self.tab_2)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_14 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.widget_14)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.parameter_selector = QtWidgets.QComboBox(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_selector.sizePolicy().hasHeightForWidth())
        self.parameter_selector.setSizePolicy(sizePolicy)
        self.parameter_selector.setObjectName("parameter_selector")
        self.horizontalLayout_20.addWidget(self.parameter_selector)
        self.parameter_option_button = QtWidgets.QPushButton(self.widget_14)
        self.parameter_option_button.setObjectName("parameter_option_button")
        self.horizontalLayout_20.addWidget(self.parameter_option_button)
        self.verticalLayout_15.addWidget(self.widget_14)
        self.parameter_widget = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameter_widget.sizePolicy().hasHeightForWidth())
        self.parameter_widget.setSizePolicy(sizePolicy)
        self.parameter_widget.setObjectName("parameter_widget")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.parameter_widget)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15.addWidget(self.parameter_widget)
        self.horizontalLayout_19.addWidget(self.groupBox_3)
        self.parameter_widget_2 = QtWidgets.QTableWidget(self.widget_13)
        self.parameter_widget_2.setObjectName("parameter_widget_2")
        self.parameter_widget_2.setColumnCount(5)
        self.parameter_widget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_widget_2.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_19.addWidget(self.parameter_widget_2)
        self.verticalLayout_17.addWidget(self.widget_13)
        self.data_history_widget = QtWidgets.QWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_history_widget.sizePolicy().hasHeightForWidth())
        self.data_history_widget.setSizePolicy(sizePolicy)
        self.data_history_widget.setObjectName("data_history_widget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.data_history_widget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_17.addWidget(self.data_history_widget)
        self.main_tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_17 = QtWidgets.QWidget(self.tab_3)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_22.setContentsMargins(0, 3, 3, 3)
        self.horizontalLayout_22.setSpacing(3)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.widget_17)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.start_label = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_label.sizePolicy().hasHeightForWidth())
        self.start_label.setSizePolicy(sizePolicy)
        self.start_label.setText("")
        self.start_label.setObjectName("start_label")
        self.horizontalLayout_22.addWidget(self.start_label)
        self.verticalLayout_18.addWidget(self.widget_17)
        self.widget_16 = QtWidgets.QWidget(self.tab_3)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_21.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_21.setSpacing(3)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.widget_16)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.end_label = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_label.sizePolicy().hasHeightForWidth())
        self.end_label.setSizePolicy(sizePolicy)
        self.end_label.setText("")
        self.end_label.setObjectName("end_label")
        self.horizontalLayout_21.addWidget(self.end_label)
        self.verticalLayout_18.addWidget(self.widget_16)
        self.widget_18 = QtWidgets.QWidget(self.tab_3)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_23.setContentsMargins(0, 3, 3, 3)
        self.horizontalLayout_23.setSpacing(3)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtWidgets.QLabel(self.widget_18)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        self.foms_label = QtWidgets.QLabel(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foms_label.sizePolicy().hasHeightForWidth())
        self.foms_label.setSizePolicy(sizePolicy)
        self.foms_label.setText("")
        self.foms_label.setObjectName("foms_label")
        self.horizontalLayout_23.addWidget(self.foms_label)
        self.verticalLayout_18.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_18.addWidget(self.widget_19)
        self.main_tab.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslateUi(Form)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Full anlaysis window")
        self.label_5.setText("Category: ")
        self.label.setText("Data to visualize: ")
        self.label_3.setText("Data overlay")
        self.add_result_button.setText("Add result")
        self.clear_button.setText("Clean")
        self.label_2.setText("Export")
        self.copy_select_button.setText("Copy selection")
        self.copy_data_button.setText("Copy")
        self.save_data_button.setText("Save")
        self.label_4.setText("FOM formula: ")
        self.fom_label.setText("FOM: ")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab), "Data analysis")
        self.groupBox_3.setTitle("Parameters and history")
        self.label_19.setText("Parameter: ")
        self.parameter_option_button.setText("Options")
        item = self.parameter_widget_2.horizontalHeaderItem(0)
        item.setText("Parameter")
        item = self.parameter_widget_2.horizontalHeaderItem(1)
        item.setText("Value")
        item = self.parameter_widget_2.horizontalHeaderItem(2)
        item.setText("Lower bound")
        item = self.parameter_widget_2.horizontalHeaderItem(3)
        item.setText("Upper bound")
        item = self.parameter_widget_2.horizontalHeaderItem(4)
        item.setText("Error")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_2), "Parameters and evolution")
        self.label_21.setText("Start")
        self.label_20.setText("End")
        self.label_22.setText("FOM: ")
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_3), "General information")

