#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(974, 1002)
        self.centralwidget = QtGui.QWidget(main_window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.workspace_box = QtGui.QGroupBox(self.centralwidget)
        self.workspace_box.setObjectName(_fromUtf8("workspace_box"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.workspace_box)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.workspace_tab = QtGui.QTabWidget(self.workspace_box)
        self.workspace_tab.setTabPosition(QtGui.QTabWidget.South)
        self.workspace_tab.setObjectName(_fromUtf8("workspace_tab"))
        self.modelisation_tab = QtGui.QWidget()
        self.modelisation_tab.setObjectName(_fromUtf8("modelisation_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.modelisation_tab)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.modelisation_mdiarea = QtGui.QMdiArea(self.modelisation_tab)
        self.modelisation_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.modelisation_mdiarea.setObjectName(_fromUtf8("modelisation_mdiarea"))
        self.verticalLayout_5.addWidget(self.modelisation_mdiarea)
        self.workspace_tab.addTab(self.modelisation_tab, _fromUtf8(""))
        self.operation_tab = QtGui.QWidget()
        self.operation_tab.setObjectName(_fromUtf8("operation_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.operation_tab)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget = QtGui.QWidget(self.operation_tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.running_operation_combo = QtGui.QComboBox(self.widget)
        self.running_operation_combo.setEditable(True)
        self.running_operation_combo.setObjectName(_fromUtf8("running_operation_combo"))
        self.horizontalLayout_3.addWidget(self.running_operation_combo)
        self.state_label = QtGui.QLabel(self.widget)
        self.state_label.setObjectName(_fromUtf8("state_label"))
        self.horizontalLayout_3.addWidget(self.state_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.stop_button = QtGui.QPushButton(self.widget)
        self.stop_button.setEnabled(False)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.horizontalLayout_3.addWidget(self.stop_button)
        self.verticalLayout_6.addWidget(self.widget)
        self.operation_mdiarea = QtGui.QMdiArea(self.operation_tab)
        self.operation_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.operation_mdiarea.setObjectName(_fromUtf8("operation_mdiarea"))
        self.verticalLayout_6.addWidget(self.operation_mdiarea)
        self.workspace_tab.addTab(self.operation_tab, _fromUtf8(""))
        self.analyse_tab = QtGui.QWidget()
        self.analyse_tab.setObjectName(_fromUtf8("analyse_tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.analyse_tab)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.analyse_mdiarea = QtGui.QMdiArea(self.analyse_tab)
        self.analyse_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.analyse_mdiarea.setObjectName(_fromUtf8("analyse_mdiarea"))
        self.verticalLayout_7.addWidget(self.analyse_mdiarea)
        self.workspace_tab.addTab(self.analyse_tab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.workspace_tab)
        self.verticalLayout.addWidget(self.workspace_box)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.file_menu = QtGui.QMenu(self.menubar)
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.new_menu = QtGui.QMenu(self.file_menu)
        self.new_menu.setObjectName(_fromUtf8("new_menu"))
        self.menuImporter = QtGui.QMenu(self.file_menu)
        self.menuImporter.setObjectName(_fromUtf8("menuImporter"))
        self.view_menu = QtGui.QMenu(self.menubar)
        self.view_menu.setObjectName(_fromUtf8("view_menu"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
#         self.language_menu = QtGui.QMenu(self.menuOption)
#         self.language_menu.setObjectName(_fromUtf8("language_menu"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        self.tools_menu = QtGui.QMenu(self.menubar)
        self.tools_menu.setObjectName(_fromUtf8("tools_menu"))
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main_window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        main_window.setStatusBar(self.statusbar)
        self.data_widget = QtGui.QDockWidget(main_window)
        self.data_widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.data_widget.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.data_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.data_widget.setObjectName(_fromUtf8("data_widget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.data_tree = QtGui.QTreeWidget(self.dockWidgetContents)
        self.data_tree.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.data_tree.setObjectName(_fromUtf8("data_tree"))
        item_0 = QtGui.QTreeWidgetItem(self.data_tree)
        item_0 = QtGui.QTreeWidgetItem(self.data_tree)
        item_0 = QtGui.QTreeWidgetItem(self.data_tree)
        self.verticalLayout_4.addWidget(self.data_tree)
        self.data_widget.setWidget(self.dockWidgetContents)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.data_widget)
        self.new_instrument_action = QtGui.QAction(main_window)
        self.new_instrument_action.setObjectName(_fromUtf8("new_instrument_action"))
        self.new_sample_action = QtGui.QAction(main_window)
        self.new_sample_action.setObjectName(_fromUtf8("new_sample_action"))
        self.new_DB_action = QtGui.QAction(main_window)
        self.new_DB_action.setObjectName(_fromUtf8("new_DB_action"))
        self.close_DB_action = QtGui.QAction(main_window)
        self.close_DB_action.setObjectName(_fromUtf8("close_DB_action"))
        self.exit_action = QtGui.QAction(main_window)
        self.exit_action.setObjectName(_fromUtf8("exit_action"))
        self.open_data_action = QtGui.QAction(main_window)
        self.open_data_action.setObjectName(_fromUtf8("open_data_action"))
        self.open_operation_action = QtGui.QAction(main_window)
        self.open_operation_action.setObjectName(_fromUtf8("open_operation_action"))
        self.DB_open_action = QtGui.QAction(main_window)
        self.DB_open_action.setObjectName(_fromUtf8("DB_open_action"))
        self.casscade_mode_action = QtGui.QAction(main_window)
        self.casscade_mode_action.setObjectName(_fromUtf8("casscade_mode_action"))
        self.tile_mode_action = QtGui.QAction(main_window)
        self.tile_mode_action.setObjectName(_fromUtf8("tile_mode_action"))
        self.new_mod_win_action = QtGui.QAction(main_window)
        self.new_mod_win_action.setObjectName(_fromUtf8("new_mod_win_action"))
        self.operation_view_mode = QtGui.QAction(main_window)
        self.operation_view_mode.setObjectName(_fromUtf8("operation_view_mode"))
        self.new_op_win_action = QtGui.QAction(main_window)
        self.new_op_win_action.setObjectName(_fromUtf8("new_op_win_action"))
        self.new_analyse_win_action = QtGui.QAction(main_window)
        self.new_analyse_win_action.setObjectName(_fromUtf8("new_analyse_win_action"))
        self.data_view_action = QtGui.QAction(main_window)
        self.data_view_action.setObjectName(_fromUtf8("data_view_action"))
        self.general_option_action = QtGui.QAction(main_window)
        self.general_option_action.setObjectName(_fromUtf8("general_option_action"))
        self.new_instrument_acition = QtGui.QAction(main_window)
        self.new_instrument_acition.setObjectName(_fromUtf8("new_instrument_acition"))
        self.new_sample_task = QtGui.QAction(main_window)
        self.new_sample_task.setObjectName(_fromUtf8("new_sample_task"))
        self.open_op_action = QtGui.QAction(main_window)
        self.open_op_action.setObjectName(_fromUtf8("open_op_action"))
        self.save_database_action = QtGui.QAction(main_window)
        self.save_database_action.setObjectName(_fromUtf8("save_database_action"))
        self.delete_action = QtGui.QAction(main_window)
        self.delete_action.setObjectName(_fromUtf8("delete_action"))
        self.help_action = QtGui.QAction(main_window)
        self.help_action.setObjectName(_fromUtf8("help_action"))
        self.old_data_import_action = QtGui.QAction(main_window)
        self.old_data_import_action.setObjectName(_fromUtf8("old_data_import_action"))
        self.french_action = QtGui.QAction(main_window)
        self.french_action.setCheckable(True)
        self.french_action.setChecked(True)
        self.french_action.setObjectName(_fromUtf8("french_action"))
        self.english_action = QtGui.QAction(main_window)
        self.english_action.setCheckable(True)
        self.english_action.setObjectName(_fromUtf8("english_action"))
        self.new_menu.addAction(self.new_instrument_action)
        self.new_menu.addAction(self.new_sample_action)
        self.new_menu.addAction(self.new_DB_action)
        self.menuImporter.addAction(self.old_data_import_action)
        self.file_menu.addAction(self.new_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.DB_open_action)
        self.file_menu.addAction(self.close_DB_action)
        self.file_menu.addAction(self.save_database_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.menuImporter.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.view_menu.addAction(self.casscade_mode_action)
        self.view_menu.addAction(self.tile_mode_action)
        self.menuOption.addAction(self.general_option_action)
#         self.menuOption.addAction(self.language_menu.menuAction())
        self.menuAide.addAction(self.help_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(main_window)
        self.workspace_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle("PyXCEL : Python software for X-ray Combined ELemental analysis")
        self.workspace_box.setTitle("Workspace: ")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.modelisation_tab), "Modeling")
        self.label.setText("Operation selection")
        self.state_label.setText("State")
        self.stop_button.setText("Stop")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.operation_tab), "Operation")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.analyse_tab), "Analysis")
        self.file_menu.setTitle("File")
        self.new_menu.setTitle("New")
        self.menuImporter.setTitle("Import")
        self.view_menu.setTitle("Display")
        self.menuOption.setTitle("Options")
#         self.language_menu.setTitle(_translate("main_window", "Langue", None))
        self.menuAide.setTitle("Help")
        self.tools_menu.setTitle("Tools")
        self.data_widget.setWindowTitle("Data widget")
        self.data_tree.headerItem().setText(0, "Data tree")
        __sortingEnabled = self.data_tree.isSortingEnabled()
        self.data_tree.setSortingEnabled(False)
        self.data_tree.topLevelItem(0).setText(0, "Instrument")
        self.data_tree.topLevelItem(1).setText(0, "Sample")
        self.data_tree.topLevelItem(2).setText(0, "Operation")
        self.data_tree.setSortingEnabled(__sortingEnabled)
        self.new_instrument_action.setText("Instrument")
        self.new_sample_action.setText("Sample")
        self.new_sample_action.setToolTip("Sample")
        self.new_DB_action.setText("Database")
        self.close_DB_action.setText("Close database")
        self.exit_action.setText("Quit")
        self.open_data_action.setText("Data")
        self.open_operation_action.setText("Operation")
        self.DB_open_action.setText("Open database")
        self.casscade_mode_action.setText("Cascade mode")
        self.tile_mode_action.setText("Aligned mode")
        self.new_mod_win_action.setText("New window")
        self.new_mod_win_action.setToolTip("New modeling window")
        self.operation_view_mode.setText("Operation")
        self.new_op_win_action.setText("New window")
        self.new_op_win_action.setToolTip("New operation window")
        self.new_analyse_win_action.setText("New window")
        self.new_analyse_win_action.setToolTip("New analysis window")
        self.data_view_action.setText("Data")
        self.general_option_action.setText("Options")
        self.new_instrument_acition.setText("New instrument")
        self.new_sample_task.setText("New sample")
        self.open_op_action.setText("Open operation")
        self.save_database_action.setText("Save database")
        self.delete_action.setText("Delete")
        self.help_action.setText("Index")
        self.old_data_import_action.setText("Old database")
        self.french_action.setText("French")
        self.english_action.setText("English")

