#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(974, 1002)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.workspace_box = QtWidgets.QGroupBox(self.centralwidget)
        self.workspace_box.setObjectName("workspace_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.workspace_box)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.workspace_tab = QtWidgets.QTabWidget(self.workspace_box)
        self.workspace_tab.setTabPosition(QtWidgets.QTabWidget.South)
        self.workspace_tab.setObjectName("workspace_tab")
        self.modelisation_tab = QtWidgets.QWidget()
        self.modelisation_tab.setObjectName("modelisation_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.modelisation_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.modelisation_mdiarea = QtWidgets.QMdiArea(self.modelisation_tab)
        self.modelisation_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.modelisation_mdiarea.setObjectName("modelisation_mdiarea")
        self.verticalLayout_5.addWidget(self.modelisation_mdiarea)
        self.workspace_tab.addTab(self.modelisation_tab, "")
        self.operation_tab = QtWidgets.QWidget()
        self.operation_tab.setObjectName("operation_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.operation_tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.operation_tab)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.running_operation_combo = QtWidgets.QComboBox(self.widget)
        self.running_operation_combo.setEditable(True)
        self.running_operation_combo.setObjectName("running_operation_combo")
        self.horizontalLayout_3.addWidget(self.running_operation_combo)
        self.state_label = QtWidgets.QLabel(self.widget)
        self.state_label.setObjectName("state_label")
        self.horizontalLayout_3.addWidget(self.state_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.stop_button = QtWidgets.QPushButton(self.widget)
        self.stop_button.setEnabled(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_3.addWidget(self.stop_button)
        self.verticalLayout_6.addWidget(self.widget)
        self.operation_mdiarea = QtWidgets.QMdiArea(self.operation_tab)
        self.operation_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.operation_mdiarea.setObjectName("operation_mdiarea")
        self.verticalLayout_6.addWidget(self.operation_mdiarea)
        self.workspace_tab.addTab(self.operation_tab, "")
        self.analyse_tab = QtWidgets.QWidget()
        self.analyse_tab.setObjectName("analyse_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.analyse_tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.analyse_mdiarea = QtWidgets.QMdiArea(self.analyse_tab)
        self.analyse_mdiarea.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.analyse_mdiarea.setObjectName("analyse_mdiarea")
        self.verticalLayout_7.addWidget(self.analyse_mdiarea)
        self.workspace_tab.addTab(self.analyse_tab, "")
        self.verticalLayout_3.addWidget(self.workspace_tab)
        self.verticalLayout.addWidget(self.workspace_box)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.new_menu = QtWidgets.QMenu(self.file_menu)
        self.new_menu.setObjectName("new_menu")
        self.menuImporter = QtWidgets.QMenu(self.file_menu)
        self.menuImporter.setObjectName("menuImporter")
        self.view_menu = QtWidgets.QMenu(self.menubar)
        self.view_menu.setObjectName("view_menu")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.language_menu = QtWidgets.QMenu(self.menuOption)
        self.language_menu.setObjectName("language_menu")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        self.tools_menu = QtWidgets.QMenu(self.menubar)
        self.tools_menu.setObjectName("tools_menu")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.data_widget = QtWidgets.QDockWidget(main_window)
        self.data_widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.data_widget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.data_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.data_widget.setObjectName("data_widget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.data_tree = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.data_tree.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.data_tree.setObjectName("data_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.data_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.data_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.data_tree)
        self.verticalLayout_4.addWidget(self.data_tree)
        self.data_widget.setWidget(self.dockWidgetContents)
        main_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.data_widget)
        self.new_instrument_action = QtWidgets.QAction(main_window)
        self.new_instrument_action.setObjectName("new_instrument_action")
        self.new_sample_action = QtWidgets.QAction(main_window)
        self.new_sample_action.setObjectName("new_sample_action")
        self.new_DB_action = QtWidgets.QAction(main_window)
        self.new_DB_action.setObjectName("new_DB_action")
        self.close_DB_action = QtWidgets.QAction(main_window)
        self.close_DB_action.setObjectName("close_DB_action")
        self.exit_action = QtWidgets.QAction(main_window)
        self.exit_action.setObjectName("exit_action")
        self.open_data_action = QtWidgets.QAction(main_window)
        self.open_data_action.setObjectName("open_data_action")
        self.open_operation_action = QtWidgets.QAction(main_window)
        self.open_operation_action.setObjectName("open_operation_action")
        self.DB_open_action = QtWidgets.QAction(main_window)
        self.DB_open_action.setObjectName("DB_open_action")
        self.casscade_mode_action = QtWidgets.QAction(main_window)
        self.casscade_mode_action.setObjectName("casscade_mode_action")
        self.tile_mode_action = QtWidgets.QAction(main_window)
        self.tile_mode_action.setObjectName("tile_mode_action")
        self.new_mod_win_action = QtWidgets.QAction(main_window)
        self.new_mod_win_action.setObjectName("new_mod_win_action")
        self.operation_view_mode = QtWidgets.QAction(main_window)
        self.operation_view_mode.setObjectName("operation_view_mode")
        self.new_op_win_action = QtWidgets.QAction(main_window)
        self.new_op_win_action.setObjectName("new_op_win_action")
        self.new_analyse_win_action = QtWidgets.QAction(main_window)
        self.new_analyse_win_action.setObjectName("new_analyse_win_action")
        self.data_view_action = QtWidgets.QAction(main_window)
        self.data_view_action.setObjectName("data_view_action")
        self.general_option_action = QtWidgets.QAction(main_window)
        self.general_option_action.setObjectName("general_option_action")
        self.new_instrument_acition = QtWidgets.QAction(main_window)
        self.new_instrument_acition.setObjectName("new_instrument_acition")
        self.new_sample_task = QtWidgets.QAction(main_window)
        self.new_sample_task.setObjectName("new_sample_task")
        self.open_op_action = QtWidgets.QAction(main_window)
        self.open_op_action.setObjectName("open_op_action")
        self.save_database_action = QtWidgets.QAction(main_window)
        self.save_database_action.setObjectName("save_database_action")
        self.delete_action = QtWidgets.QAction(main_window)
        self.delete_action.setObjectName("delete_action")
        self.help_action = QtWidgets.QAction(main_window)
        self.help_action.setObjectName("help_action")
        self.old_data_import_action = QtWidgets.QAction(main_window)
        self.old_data_import_action.setObjectName("old_data_import_action")
        self.french_action = QtWidgets.QAction(main_window)
        self.french_action.setCheckable(True)
        self.french_action.setChecked(True)
        self.french_action.setObjectName("french_action")
        self.english_action = QtWidgets.QAction(main_window)
        self.english_action.setCheckable(True)
        self.english_action.setObjectName("english_action")
        self.new_menu.addAction(self.new_instrument_action)
        self.new_menu.addAction(self.new_sample_action)
        self.new_menu.addAction(self.new_DB_action)
        self.menuImporter.addAction(self.old_data_import_action)
        self.file_menu.addAction(self.new_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.DB_open_action)
        self.file_menu.addAction(self.close_DB_action)
        self.file_menu.addAction(self.save_database_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.menuImporter.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.view_menu.addAction(self.casscade_mode_action)
        self.view_menu.addAction(self.tile_mode_action)
        self.menuOption.addAction(self.general_option_action)
        self.menuOption.addAction(self.language_menu.menuAction())
        self.menuAide.addAction(self.help_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(main_window)
        self.workspace_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle("PyXCEL : Python software for X-ray Combined ELemental analysis")
        self.workspace_box.setTitle("Workspace: ")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.modelisation_tab), "Modeling")
        self.label.setText("Operation selection")
        self.state_label.setText("State: ")
        self.stop_button.setText("Stop")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.operation_tab), "Operation")
        self.workspace_tab.setTabText(self.workspace_tab.indexOf(self.analyse_tab), "Analysis")
        self.file_menu.setTitle("File")
        self.new_menu.setTitle("New")
        self.menuImporter.setTitle("Import")
        self.view_menu.setTitle("Display")
        self.menuOption.setTitle("Options")
        self.language_menu.setTitle("Language")
        self.menuAide.setTitle("Help")
        self.tools_menu.setTitle("Tools")
        self.data_widget.setWindowTitle("Data")
        self.data_tree.headerItem().setText(0, "Name")
        __sortingEnabled = self.data_tree.isSortingEnabled()
        self.data_tree.setSortingEnabled(False)
        self.data_tree.topLevelItem(0).setText(0, "Instrument")
        self.data_tree.topLevelItem(1).setText(0, "Sample")
        self.data_tree.topLevelItem(2).setText(0, "Operation")
        self.data_tree.setSortingEnabled(__sortingEnabled)
        self.new_instrument_action.setText("Instrument")
        self.new_sample_action.setText("Sample")
        self.new_sample_action.setToolTip("Sample")
        self.new_DB_action.setText("Database")
        self.close_DB_action.setText("Close database")
        self.exit_action.setText("Quit")
        self.open_data_action.setText("Data")
        self.open_operation_action.setText("Operation")
        self.DB_open_action.setText("Open database")
        self.casscade_mode_action.setText("Cascade mode")
        self.tile_mode_action.setText("Aligned mode")
        self.new_mod_win_action.setText("New window")
        self.new_mod_win_action.setToolTip("Create a new modeling window")
        self.operation_view_mode.setText("Operation")
        self.new_op_win_action.setText("New window")
        self.new_op_win_action.setToolTip("Create new operation window")
        self.new_analyse_win_action.setText("New window")
        self.new_analyse_win_action.setToolTip("New analysis window")
        self.data_view_action.setText("Data: ")
        self.general_option_action.setText("Options")
        self.new_instrument_acition.setText("New instrument")
        self.new_sample_task.setText("New sample")
        self.open_op_action.setText("Open operation")
        self.save_database_action.setText("Save database")
        self.delete_action.setText("Delete")
        self.help_action.setText("Index")
        self.old_data_import_action.setText("Old database")
        self.french_action.setText("French")
        self.english_action.setText("English")

