#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\op_graph.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(587, 515)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selecting_widget = QtWidgets.QWidget(Form)
        self.selecting_widget.setObjectName("selecting_widget")
        self.selecting_layout = QtWidgets.QHBoxLayout(self.selecting_widget)
        self.selecting_layout.setContentsMargins(0, 0, 0, 0)
        self.selecting_layout.setSpacing(0)
        self.selecting_layout.setObjectName("selecting_layout")
        self.data_label = QtWidgets.QLabel(self.selecting_widget)
        self.data_label.setEnabled(False)
        self.data_label.setObjectName("data_label")
        self.selecting_layout.addWidget(self.data_label)
        self.choose_data_combo = QtWidgets.QComboBox(self.selecting_widget)
        self.choose_data_combo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_data_combo.sizePolicy().hasHeightForWidth())
        self.choose_data_combo.setSizePolicy(sizePolicy)
        self.choose_data_combo.setObjectName("choose_data_combo")
        self.selecting_layout.addWidget(self.choose_data_combo)
        self.verticalLayout.addWidget(self.selecting_widget)
        self.fom_widget = QtWidgets.QWidget(Form)
        self.fom_widget.setObjectName("fom_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fom_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.fom_selector = QtWidgets.QComboBox(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_selector.sizePolicy().hasHeightForWidth())
        self.fom_selector.setSizePolicy(sizePolicy)
        self.fom_selector.setObjectName("fom_selector")
        self.horizontalLayout.addWidget(self.fom_selector)
        self.fom_label = QtWidgets.QLabel(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_label.sizePolicy().hasHeightForWidth())
        self.fom_label.setSizePolicy(sizePolicy)
        self.fom_label.setObjectName("fom_label")
        self.horizontalLayout.addWidget(self.fom_label)
        self.fom_line = QtWidgets.QLineEdit(self.fom_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fom_line.sizePolicy().hasHeightForWidth())
        self.fom_line.setSizePolicy(sizePolicy)
        self.fom_line.setObjectName("fom_line")
        self.horizontalLayout.addWidget(self.fom_line)
        self.verticalLayout.addWidget(self.fom_widget)
        self.data_treatment_widget = QtWidgets.QWidget(Form)
        self.data_treatment_widget.setObjectName("data_treatment_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.data_treatment_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.data_treatment_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.data_treatment_button = QtWidgets.QPushButton(self.data_treatment_widget)
        self.data_treatment_button.setObjectName("data_treatment_button")
        self.horizontalLayout_2.addWidget(self.data_treatment_button)
        self.verticalLayout.addWidget(self.data_treatment_widget)
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.main_layout = QtWidgets.QVBoxLayout(self.widget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.main_widget = QtWidgets.QWidget(self.widget)
        self.main_widget.setObjectName("main_widget")
        self.main_layout.addWidget(self.main_widget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle("Operation graph")
        self.data_label.setText("Data to visualize: ")
        self.label.setText("FOM formula: ")
        self.fom_label.setText("FOM: ")
        self.label_2.setText("Data processing: ")
        self.data_treatment_button.setText("Select operation: ")

