#pylint: disable-all
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tab_editor.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.element_combo = QtWidgets.QComboBox(self.widget_3)
        self.element_combo.setEditable(True)
        self.element_combo.setObjectName("element_combo")
        self.horizontalLayout_2.addWidget(self.element_combo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.parameter_combo = QtWidgets.QComboBox(self.widget_3)
        self.parameter_combo.setEditable(False)
        self.parameter_combo.setObjectName("parameter_combo")
        self.horizontalLayout_2.addWidget(self.parameter_combo)
        self.add_button = QtWidgets.QPushButton(self.widget_3)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.delete_button = QtWidgets.QPushButton(self.widget_3)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_2.addWidget(self.delete_button)
        self.verticalLayout.addWidget(self.widget_3)
        self.parameter_tab = QtWidgets.QTableWidget(Form)
        self.parameter_tab.setObjectName("parameter_tab")
        self.parameter_tab.setColumnCount(7)
        self.parameter_tab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter_tab.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.parameter_tab)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.load_button = QtWidgets.QPushButton(self.widget)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout.addWidget(self.load_button)
        spacerItem1 = QtWidgets.QSpacerItem(439, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancel_button = QtWidgets.QPushButton(self.widget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.validate_button = QtWidgets.QPushButton(self.widget)
        self.validate_button.setObjectName("validate_button")
        self.horizontalLayout.addWidget(self.validate_button)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Elément : "))
        self.label_2.setText(_translate("Form", "Paramètre : "))
        self.add_button.setText(_translate("Form", "Ajouter"))
        self.delete_button.setText(_translate("Form", "Supprimer"))
        item = self.parameter_tab.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Paramètre"))
        item = self.parameter_tab.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Affiner"))
        item = self.parameter_tab.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Valeur"))
        item = self.parameter_tab.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Min"))
        item = self.parameter_tab.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Max"))
        item = self.parameter_tab.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Incertitude"))
        item = self.parameter_tab.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Groupe"))
        self.save_button.setText(_translate("Form", "Enregistrer"))
        self.load_button.setText(_translate("Form", "Charger"))
        self.cancel_button.setText(_translate("Form", "Annuler"))
        self.validate_button.setText(_translate("Form", "Valider"))

